### ISSUE TITLE
code for targets_values_normalize

### ISSUE THREAD

**Issue by Tsinghua-gongjing** [shu65/open-problems-multimodal#8]
Hi, thank you for the great work and congratulations being 1st in the competition.

The solution is clear and the code is well organized. It seems an [(targets_values_normalize)](https://github.com/shu65/open-problems-multimodal/blob/4dc5b1375c26c1c06ea35ea450e8bdc12f83f7fb/script/make_cite_input_mask.py#L234) function is lost while uploading. Could you please have a look?

Best

**Comment by samgoodman** [comment]
The file was deleted, but its history is still tracked:

https://github.com/shu65/open-problems-multimodal/blob/e3c01e5d76624cd7ebcc2fc17d2ef76c22877401/ss_opm/utility/targets_values_normalize.py

**Comment by shu65** [comment]
Thank you for the bug report. I fixed this bug.
https://github.com/shu65/open-problems-multimodal/pull/9
